services:
  # Chroma vector database service
  chroma:
    image: chromadb/chroma
    container_name: k6-mcp-chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    
    # Persistent volume for chroma data
    volumes:
      - chroma_data:/chroma/chroma
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 128M
    
    # Labels
    labels:
      - "com.k6-mcp.description=Chroma Vector Database"
      - "com.k6-mcp.version=latest"
      - "maintainer=k6-mcp-team"

# Persistent volumes
volumes:
  chroma_data:
    driver: local