version: '3.8'

services:
  k6-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: k6-mcp:latest
    container_name: k6-mcp-server
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["/usr/local/bin/k6-mcp", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: "65532:65532"  # nonroot user from distroless
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    
    # Temporary filesystem for any temp files
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    
    # Labels
    labels:
      - "com.k6-mcp.description=k6 MCP Server"
      - "com.k6-mcp.version=1.0.0"
      - "maintainer=k6-mcp-team"

  # Example service showing how to use k6-mcp in a stack
  # Uncomment and modify as needed
  #
  # example-app:
  #   image: your-app:latest
  #   depends_on:
  #     k6-mcp:
  #       condition: service_healthy
  #   environment:
  #     - MCP_SERVER_COMMAND=docker exec k6-mcp-server /usr/local/bin/k6-mcp